// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_checkout.proto

package specmesh.examples.schema_demo.model;

public final class UserCheckoutOuterClass {
  private UserCheckoutOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserCheckoutOrBuilder extends
      // @@protoc_insertion_point(interface_extends:specmesh.examples.schema_demo.model.UserCheckout)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 userId = 1;</code>
     * @return The userId.
     */
    int getUserId();

    /**
     * <code>int32 itemCount = 2;</code>
     * @return The itemCount.
     */
    int getItemCount();

    /**
     * <code>string basketPrice = 3;</code>
     * @return The basketPrice.
     */
    java.lang.String getBasketPrice();
    /**
     * <code>string basketPrice = 3;</code>
     * @return The bytes for basketPrice.
     */
    com.google.protobuf.ByteString
        getBasketPriceBytes();
  }
  /**
   * Protobuf type {@code specmesh.examples.schema_demo.model.UserCheckout}
   */
  public static final class UserCheckout extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:specmesh.examples.schema_demo.model.UserCheckout)
      UserCheckoutOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserCheckout.newBuilder() to construct.
    private UserCheckout(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserCheckout() {
      basketPrice_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UserCheckout();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return specmesh.examples.schema_demo.model.UserCheckoutOuterClass.internal_static_specmesh_examples_schema_demo_model_UserCheckout_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return specmesh.examples.schema_demo.model.UserCheckoutOuterClass.internal_static_specmesh_examples_schema_demo_model_UserCheckout_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              specmesh.examples.schema_demo.model.UserCheckoutOuterClass.UserCheckout.class, specmesh.examples.schema_demo.model.UserCheckoutOuterClass.UserCheckout.Builder.class);
    }

    public static final int USERID_FIELD_NUMBER = 1;
    private int userId_ = 0;
    /**
     * <code>int32 userId = 1;</code>
     * @return The userId.
     */
    @java.lang.Override
    public int getUserId() {
      return userId_;
    }

    public static final int ITEMCOUNT_FIELD_NUMBER = 2;
    private int itemCount_ = 0;
    /**
     * <code>int32 itemCount = 2;</code>
     * @return The itemCount.
     */
    @java.lang.Override
    public int getItemCount() {
      return itemCount_;
    }

    public static final int BASKETPRICE_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object basketPrice_ = "";
    /**
     * <code>string basketPrice = 3;</code>
     * @return The basketPrice.
     */
    @java.lang.Override
    public java.lang.String getBasketPrice() {
      java.lang.Object ref = basketPrice_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        basketPrice_ = s;
        return s;
      }
    }
    /**
     * <code>string basketPrice = 3;</code>
     * @return The bytes for basketPrice.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBasketPriceBytes() {
      java.lang.Object ref = basketPrice_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        basketPrice_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userId_ != 0) {
        output.writeInt32(1, userId_);
      }
      if (itemCount_ != 0) {
        output.writeInt32(2, itemCount_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(basketPrice_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, basketPrice_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, userId_);
      }
      if (itemCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, itemCount_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(basketPrice_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, basketPrice_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof specmesh.examples.schema_demo.model.UserCheckoutOuterClass.UserCheckout)) {
        return super.equals(obj);
      }
      specmesh.examples.schema_demo.model.UserCheckoutOuterClass.UserCheckout other = (specmesh.examples.schema_demo.model.UserCheckoutOuterClass.UserCheckout) obj;

      if (getUserId()
          != other.getUserId()) return false;
      if (getItemCount()
          != other.getItemCount()) return false;
      if (!getBasketPrice()
          .equals(other.getBasketPrice())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId();
      hash = (37 * hash) + ITEMCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getItemCount();
      hash = (37 * hash) + BASKETPRICE_FIELD_NUMBER;
      hash = (53 * hash) + getBasketPrice().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static specmesh.examples.schema_demo.model.UserCheckoutOuterClass.UserCheckout parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static specmesh.examples.schema_demo.model.UserCheckoutOuterClass.UserCheckout parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static specmesh.examples.schema_demo.model.UserCheckoutOuterClass.UserCheckout parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static specmesh.examples.schema_demo.model.UserCheckoutOuterClass.UserCheckout parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static specmesh.examples.schema_demo.model.UserCheckoutOuterClass.UserCheckout parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static specmesh.examples.schema_demo.model.UserCheckoutOuterClass.UserCheckout parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static specmesh.examples.schema_demo.model.UserCheckoutOuterClass.UserCheckout parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static specmesh.examples.schema_demo.model.UserCheckoutOuterClass.UserCheckout parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static specmesh.examples.schema_demo.model.UserCheckoutOuterClass.UserCheckout parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static specmesh.examples.schema_demo.model.UserCheckoutOuterClass.UserCheckout parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static specmesh.examples.schema_demo.model.UserCheckoutOuterClass.UserCheckout parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static specmesh.examples.schema_demo.model.UserCheckoutOuterClass.UserCheckout parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(specmesh.examples.schema_demo.model.UserCheckoutOuterClass.UserCheckout prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code specmesh.examples.schema_demo.model.UserCheckout}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:specmesh.examples.schema_demo.model.UserCheckout)
        specmesh.examples.schema_demo.model.UserCheckoutOuterClass.UserCheckoutOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return specmesh.examples.schema_demo.model.UserCheckoutOuterClass.internal_static_specmesh_examples_schema_demo_model_UserCheckout_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return specmesh.examples.schema_demo.model.UserCheckoutOuterClass.internal_static_specmesh_examples_schema_demo_model_UserCheckout_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                specmesh.examples.schema_demo.model.UserCheckoutOuterClass.UserCheckout.class, specmesh.examples.schema_demo.model.UserCheckoutOuterClass.UserCheckout.Builder.class);
      }

      // Construct using specmesh.examples.schema_demo.model.UserCheckoutOuterClass.UserCheckout.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        userId_ = 0;
        itemCount_ = 0;
        basketPrice_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return specmesh.examples.schema_demo.model.UserCheckoutOuterClass.internal_static_specmesh_examples_schema_demo_model_UserCheckout_descriptor;
      }

      @java.lang.Override
      public specmesh.examples.schema_demo.model.UserCheckoutOuterClass.UserCheckout getDefaultInstanceForType() {
        return specmesh.examples.schema_demo.model.UserCheckoutOuterClass.UserCheckout.getDefaultInstance();
      }

      @java.lang.Override
      public specmesh.examples.schema_demo.model.UserCheckoutOuterClass.UserCheckout build() {
        specmesh.examples.schema_demo.model.UserCheckoutOuterClass.UserCheckout result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public specmesh.examples.schema_demo.model.UserCheckoutOuterClass.UserCheckout buildPartial() {
        specmesh.examples.schema_demo.model.UserCheckoutOuterClass.UserCheckout result = new specmesh.examples.schema_demo.model.UserCheckoutOuterClass.UserCheckout(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(specmesh.examples.schema_demo.model.UserCheckoutOuterClass.UserCheckout result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.userId_ = userId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.itemCount_ = itemCount_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.basketPrice_ = basketPrice_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof specmesh.examples.schema_demo.model.UserCheckoutOuterClass.UserCheckout) {
          return mergeFrom((specmesh.examples.schema_demo.model.UserCheckoutOuterClass.UserCheckout)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(specmesh.examples.schema_demo.model.UserCheckoutOuterClass.UserCheckout other) {
        if (other == specmesh.examples.schema_demo.model.UserCheckoutOuterClass.UserCheckout.getDefaultInstance()) return this;
        if (other.getUserId() != 0) {
          setUserId(other.getUserId());
        }
        if (other.getItemCount() != 0) {
          setItemCount(other.getItemCount());
        }
        if (!other.getBasketPrice().isEmpty()) {
          basketPrice_ = other.basketPrice_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                userId_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                itemCount_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                basketPrice_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int userId_ ;
      /**
       * <code>int32 userId = 1;</code>
       * @return The userId.
       */
      @java.lang.Override
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>int32 userId = 1;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(int value) {
        
        userId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 userId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0;
        onChanged();
        return this;
      }

      private int itemCount_ ;
      /**
       * <code>int32 itemCount = 2;</code>
       * @return The itemCount.
       */
      @java.lang.Override
      public int getItemCount() {
        return itemCount_;
      }
      /**
       * <code>int32 itemCount = 2;</code>
       * @param value The itemCount to set.
       * @return This builder for chaining.
       */
      public Builder setItemCount(int value) {
        
        itemCount_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 itemCount = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearItemCount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        itemCount_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object basketPrice_ = "";
      /**
       * <code>string basketPrice = 3;</code>
       * @return The basketPrice.
       */
      public java.lang.String getBasketPrice() {
        java.lang.Object ref = basketPrice_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          basketPrice_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string basketPrice = 3;</code>
       * @return The bytes for basketPrice.
       */
      public com.google.protobuf.ByteString
          getBasketPriceBytes() {
        java.lang.Object ref = basketPrice_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          basketPrice_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string basketPrice = 3;</code>
       * @param value The basketPrice to set.
       * @return This builder for chaining.
       */
      public Builder setBasketPrice(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        basketPrice_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string basketPrice = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearBasketPrice() {
        basketPrice_ = getDefaultInstance().getBasketPrice();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string basketPrice = 3;</code>
       * @param value The bytes for basketPrice to set.
       * @return This builder for chaining.
       */
      public Builder setBasketPriceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        basketPrice_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:specmesh.examples.schema_demo.model.UserCheckout)
    }

    // @@protoc_insertion_point(class_scope:specmesh.examples.schema_demo.model.UserCheckout)
    private static final specmesh.examples.schema_demo.model.UserCheckoutOuterClass.UserCheckout DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new specmesh.examples.schema_demo.model.UserCheckoutOuterClass.UserCheckout();
    }

    public static specmesh.examples.schema_demo.model.UserCheckoutOuterClass.UserCheckout getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserCheckout>
        PARSER = new com.google.protobuf.AbstractParser<UserCheckout>() {
      @java.lang.Override
      public UserCheckout parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<UserCheckout> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserCheckout> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public specmesh.examples.schema_demo.model.UserCheckoutOuterClass.UserCheckout getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_specmesh_examples_schema_demo_model_UserCheckout_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_specmesh_examples_schema_demo_model_UserCheckout_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023user_checkout.proto\022#specmesh.examples" +
      ".schema_demo.model\"F\n\014UserCheckout\022\016\n\006us" +
      "erId\030\001 \001(\005\022\021\n\titemCount\030\002 \001(\005\022\023\n\013basketP" +
      "rice\030\003 \001(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_specmesh_examples_schema_demo_model_UserCheckout_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_specmesh_examples_schema_demo_model_UserCheckout_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_specmesh_examples_schema_demo_model_UserCheckout_descriptor,
        new java.lang.String[] { "UserId", "ItemCount", "BasketPrice", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
